# Generated by Django 6.0.7 on 2026-07-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xauusdcandle',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='accountstate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ledgerhistory',
            name='action',
        ),
        migrations.AddField(
            model_name='accountstate',
            name='initial_capital',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountstate',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountstate',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='accountstate',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ledgerhistory',
            name='delta',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgerhistory',
            name='resulting_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ledgerhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='xauusdcandle',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='xauusdcandle',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
