# Generated by Django migrations helper
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_xauusdcandle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerhistory',
            name='action',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
    ]
